version: '3.8'

services:
  varico-web:
    restart: always
    build:
      context: ./apps/varico-web
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - varico-api

  varico-api:
    restart: always
    build:
      context: ./apps/varico-api/
      dockerfile: ./src/Varico.Api/Dockerfile
    ports:
      - "5123:8080"  
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: 